[tool.poetry]
name = "enphase-home-api-client"
version = "0.0.1"
description = "Enphase API Client"
authors = [
    "Schipper <107776081+TheSchipper@users.noreply.github.com>",
]
packages = [{include = "enphase_home_api_client"}]


[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"