[tool.poetry]
name = "enphase-home-api-client"
version = "0.0.1"
description = "Enphase API Client"
authors = [
    "Schipper <schipper@doggy.wag>",
]


[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"